### ISSUE TITLE
acli api:environments:database-backup-download should not return JSON but actually download the backup

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#497] opened 2021-03-26 14:57 UTC
Currently `api:environments:database-backup-download` is not helpful. Acquia CLI should request an octet stream instead of JSON for download endpoints. Cloud API will then handle the redirect for it.

```
$ acli api:environments:database-backup-download myapp.prod myapp 161486477
{
    "url": "https:\/\/myapp.prod.acquia-sites.com\/AH_DOWNLOAD?t=1616760905&d=\/mnt\/gfs\/myapp.prod\/backups\/prod-myapp-myapp-2021-03-21.sql.gz&prod=ff098l4bdeb4379aa680841a5211db36919",
    "expires_at": "2021-03-26T12:25:05+00:00",
    "_links": {
        "self": {
            "href": "https:\/\/cloud.acquia.com\/api\/environments\/23767-c891e736-8678-437b-97ab-ff098l4bdeb437\/databases\/myapp\/backups\/161486477\/actions\/download"
        },
        "parent": {
            "href": "https:\/\/cloud.acquia.com\/api\/environments\/23767-c891e736-8678-437b-97ab-ff098l4bdeb437\/databases\/myapp\/backups\/161486477\/actions"
        },
        "notification": {
            "href": "https:\/\/cloud.acquia.com\/api\/notifications\/e4okh531b-3d53-4d35-8e80-5c41lkjd4940af"
        }
    }
}
```

**Comment by ba66e77** [comment] 2021-03-26 16:08
actually, @anavarre , it _is_ helpful to have it display the URL. There are no other options that I can find to see what the actual generated file name is. For my specific use-case at the moment, what I need to do is see if the filename contains the word "FAILED". So could we use some option flag to display vs actually download the file?

**Comment by anavarre** [comment] 2021-03-26 16:11
I think the expectation would still be that we'd directly download the file, which doesn't prevent us from first spitting out helpful information first.

**Comment by ba66e77** [comment] 2021-03-26 16:14
Could we have an option to just spit out the info? I don't want to actually download a 64G db backup just to see the file name

**Comment by anavarre** [comment] 2021-03-26 16:19
Sure, could be this or a yes/no prompt to proceed with the download.

**Comment by grasmash** [comment] 2021-05-04 22:41
This is basically what pull:db does— download the latest back up. I believe the API command is behaving as intended can we close this?

**Comment by anavarre** [comment] 2021-05-05 06:59
I still think the API is misleading (which could be something we'd chase with the corresponding team directly) because `database-backup-download` makes you believe you're going to be able to download a given DB backup. `database-backup-info` would be more accurate in this instance.

Also, I think what @ba66e77 wanted to achieve here is a) inspection of the backup to be downloaded and b) ability to pull any arbitrary DB backup.

**Comment by ba66e77** [comment] 2021-05-05 11:52
I think the functionality of the endpoint is fine, but agree with Aurelien's suggestion that the name should be changed to `database-backup-info` to avoid confusion. With the command title as it is I would expect it to actually download the file.

**Comment by grasmash** [comment] 2021-05-05 13:16
I'm happy with that, but I'd like to close this issue and open an internal issue for Cloud API to request that change. This does not seem like it's in the scope of Acquia CLI.

**Closed** 2021-05-05 13:18 UTC
