### ISSUE TITLE
Cannot pull from the Cloud Platform on Windows

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#531] opened 2021-04-26 12:59 UTC
Initial report from the customer. Still waiting to have more info about the specific Win version + how ACLI was installed.

```
(snip)
Pulling code from the Cloud Platform...

PHP Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in phar://C:/Users/foo/bin/acli/vendor/symfony/process/Pipes/WindowsPipes.php:74
Stack trace:
#0 phar://C:/Users/foo/bin/acli/vendor/symfony/process/Pipes/WindowsPipes.php(74): fclose(false)
#1 phar://C:/Users/foo/bin/acli/vendor/symfony/process/Process.php(1304): Symfony\Component\Process\Pipes\WindowsPipes->__construct(NULL, true)
#2 phar://C:/Users/foo/bin/acli/vendor/symfony/process/Process.php(302): Symfony\Component\Process\Process->getDescriptors()
#3 phar://C:/Users/foo/bin/acli/src/Helpers/LocalMachineHelper.php(121): Symfony\Component\Process\Process->start(NULL)
#4 phar://C:/Users/foo/bin/acli/src/Helpers/LocalMachineHelper.php(66): Acquia\Cli\Helpers\LocalMachineHelper->executeProcess(Object(Symfony\Component\Process\Process), NULL)
#5 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommandBase.php(477): Acquia\Cli\Helpers\LocalMachineHelper->execute(Array, NULL, 'C:\\xampp\\nyscom...', false)
#6 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommandBase.php(201): Acquia\Cli\Command\Pull\PullCommandBase->isLocalGitRepoDirty()
#7 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommandBase.php(98): Acquia\Cli\Command\Pull\PullCommandBase->pullCodeFromCloud(Object(AcquiaCloudApi\Response\EnvironmentResponse), Object(Closure))
#8 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommand.php(50): Acquia\Cli\Command\Pull\PullCommandBase->pullCode(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Command/Command.php(256): Acquia\Cli\Command\Pull\PullCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/Users/foo/bin/acli/src/Command/CommandBase.php(405): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Application.php(989): Acquia\Cli\Command\CommandBase->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Acquia\Cli\Command\Pull\PullCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar://C:/Users/foo/bin/acli/bin/acli(86): Symfony\Component\Console\Application->run()
#15 C:\Users\foo\bin\acli(14): require('phar://C:/Users...')
#16 {main}
thrown in phar://C:/Users/foo/bin/acli/vendor/symfony/process/Pipes/WindowsPipes.php on line 74

Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in phar://C:/Users/foo/bin/acli/vendor/symfony/process/Pipes/WindowsPipes.php:74
Stack trace:
#0 phar://C:/Users/foo/bin/acli/vendor/symfony/process/Pipes/WindowsPipes.php(74): fclose(false)
#1 phar://C:/Users/foo/bin/acli/vendor/symfony/process/Process.php(1304): Symfony\Component\Process\Pipes\WindowsPipes->__construct(NULL, true)
#2 phar://C:/Users/foo/bin/acli/vendor/symfony/process/Process.php(302): Symfony\Component\Process\Process->getDescriptors()
#3 phar://C:/Users/foo/bin/acli/src/Helpers/LocalMachineHelper.php(121): Symfony\Component\Process\Process->start(NULL)
#4 phar://C:/Users/foo/bin/acli/src/Helpers/LocalMachineHelper.php(66): Acquia\Cli\Helpers\LocalMachineHelper->executeProcess(Object(Symfony\Component\Process\Process), NULL)
#5 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommandBase.php(477): Acquia\Cli\Helpers\LocalMachineHelper->execute(Array, NULL, 'C:\\xampp\\nyscom...', false)
#6 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommandBase.php(201): Acquia\Cli\Command\Pull\PullCommandBase->isLocalGitRepoDirty()
#7 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommandBase.php(98): Acquia\Cli\Command\Pull\PullCommandBase->pullCodeFromCloud(Object(AcquiaCloudApi\Response\EnvironmentResponse), Object(Closure))
#8 phar://C:/Users/foo/bin/acli/src/Command/Pull/PullCommand.php(50): Acquia\Cli\Command\Pull\PullCommandBase->pullCode(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Command/Command.php(256): Acquia\Cli\Command\Pull\PullCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/Users/foo/bin/acli/src/Command/CommandBase.php(405): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Application.php(989): Acquia\Cli\Command\CommandBase->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Acquia\Cli\Command\Pull\PullCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://C:/Users/foo/bin/acli/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar://C:/Users/foo/bin/acli/bin/acli(86): Symfony\Component\Console\Application->run()
#15 C:\Users\foo\bin\acli(14): require('phar://C:/Users...')
#16 {main}
thrown in phar://C:/Users/foo/bin/acli/vendor/symfony/process/Pipes/WindowsPipes.php on line 74
```

**Comment by anavarre** [comment] 2021-04-29 12:24
Customer confirmed the following:

```
Edition Windows 10 Enterprise
Version 1803
OS build 17134.2087
I'm using GIT Bash
```

**Comment by grasmash** [comment] 2021-05-04 20:01
ACLI Version?

**Comment by danepowell** [comment] 2021-05-04 22:21
1803 is a _very_ old version of Windows. The only reference I could find to this kind of error online suggested that it's due to an old version of Windows: https://laracasts.com/discuss/channels/laravel/fclose-argument-1-stream-must-be-of-type-resource-bool-given?reply=699896

However I can't fathom what the root cause would be. If anything, it seems like a Symfony bug. And unfortunately I'm blocked on testing by https://github.com/acquia/cli/issues/535 . The fact that the customer _isn't_ seeing that error suggests they are also using a very old version of ACLI.

Also I'm assuming "Cloud Platform to Cloud IDE" is a typo, I don't see how Cloud IDE has anything to do with this if Windows is involved.

**Comment by grasmash** [comment] 2021-05-04 22:34
I did a cursory examination of the call stack I didn’t see anything that would cause this. I would also guess that this is a combination of an old version of ACLI and an old version of windows. 

I would like to know if this error continues on the newest version of ACLI. If we don’t get any feedback about that, let’s close it.

**Comment by anavarre** [comment] 2021-05-05 07:02
> ACLI Version?

When I created the issue, customer was using ACLI 1.10.0. Sorry I thought I had shared it here.

**Comment by danepowell** [comment] 2021-05-05 14:53
> I did a cursory examination of the call stack

Likewise, I found nothing all the way down to Symfony's call to `fopen` / `fclose`. But again, testing is hampered by #535. I can circle back after that's fixed, but I still think the most likely root cause is the old Windows version.

**Comment by grasmash** [comment] 2021-12-09 00:07
I also think we should close this. It seems very unlikely but it’s something that we can address in ACLI itself.

**Closed by grasmash** 2021-12-09 00:07 UTC
Labels: bug
