### ISSUE TITLE
On macOS 10.15.7 Catalina, any operation involving the spinner erases any previous output

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#467] opened 2021-03-08 17:23 UTC
Observed live with user testing Acquia CLI 1.8.1. When the spinner kicks in, every output on screen is erased until the spinner is at the top of the screen. Happened when:

- Waiting for an SSH key to be uploaded to the Cloud Platform
- Waiting for the IDE to be provisioned

**Comment by grasmash** [comment] 2021-03-08 17:40
I don't think I understand. Just tested on OSX Mojave in terminal app:
![image](https://user-images.githubusercontent.com/539205/110359466-85a34f00-800b-11eb-9370-584f5d296515.png)

**Comment by anavarre** [comment] 2021-03-08 17:42
If you had the issue, all other lines but the last one would have been erased (but the one with the spinner) as if you had typed `clear`.

**Comment by grasmash** [comment] 2021-03-08 17:44
Technically, the spinner is a Symfony Console progress bar. I wonder if this happen with all progress bar implementations.

**Comment by grasmash** [comment] 2021-03-08 17:57
I'm not able to fix this without having a way to reproduce it.

**Comment by pratikpp** [comment] 2021-03-08 17:59
I can share my screen and show it to you - how it looks like

**Comment by grasmash** [comment] 2021-03-08 19:37
I watched you video but it didn't actually show a bug, everything looked as expected.

**Comment by pratikpp** [comment] 2021-03-09 06:39
Check the video at 4:30 min and you will see how the commands in the terminal window are deleted.

**Comment by grasmash** [comment] 2021-03-10 19:02
So it only happened once but worked most of the time?

**Comment by anavarre** [comment] 2021-03-11 10:02
In the UX review Pratik and I participated in it was happening always. Pratik indicated it doesn't happen when in full screen mode. But the default Mac terminal is never in full screen mode by default.

**Comment by danepowell** [comment] 2021-03-11 19:01
I can confirm that this is a regression introduced in 1.8.0. I can reproduce it on the Catalina native terminal and iTerm2 in windowed mode. I use ZSH normally but also reproduced it using Bash.

If I increase the size of the terminal window past some point (it's not obvious which width or why), or if I downgrade to 1.7.2, the bug goes away.

**Comment by danepowell** [comment] 2021-03-11 19:47
D'oh! In fact this is not a regression, it's been around since 1.1.0 or earlier (I'm having trouble testing earlier versions).

What makes it tricky to reproduce is that the terminal has to be just a few characters wider than the "waiting for dns to propagate" line. If the terminal is too narrow and that message wraps, or if it's much wider, the bug doesn't occur.

That message changed in 1.8.0 which is why it appeared to be a regression, but that's just coincidence.

**Comment by danepowell** [comment] 2021-03-11 20:20
This should fix the issue if anyone wants to help test: https://github.com/symfony/symfony/pull/40450

We can either wait for that to be merged and then update Symfony, or apply it as a patch if we want it sooner.

**Comment by grasmash** [comment] 2021-03-12 16:03
I can reproduce the bug with a small terminal window. I can confirm via a manual test that the upstream change does resolve the issue.

**Closed** 2021-03-14 19:17 UTC
Labels: bug
