### ISSUE TITLE
Infinite memory usage results in kill during `acli auth:login -n`

### ISSUE THREAD

**Issue by rfay** [acquia/cli#433] opened 2021-02-25 19:57 UTC
I'm implementing Acquia integration into [ddev](https://github.com/drud/ddev) in https://github.com/drud/ddev/pull/2837 and all was going well until tests started reporting failures during authentication (`acli auth:login -n --key="${ACQUIA_API_KEY}" --secret="${ACQUIA_API_SECRET}"`)

It turns out that acli uses up all available memory and then gets killed. 

This seems to have begin in 1.7.0, at least I can't recreate it in 1.6.0

This seems to be intermittent, but when it starts happening it happens a lot. 

The ddev integration is already in prerelease, see https://github.com/drud/ddev/releases/tag/v1.17.0-alpha5, which has instructions. This behavior appeared when I upgraded the docker image and picked up 1.7.0 AFAICT.

**Comment by danepowell** [comment] 2021-02-25 22:21
I cannot reproduce this. Do you have any additional info that would help to reproduce it?

There are some problems with authentication in 1.7.0 that we expect to resolve in 1.7.1 imminently, but I wouldn't expect them to cause a memory leak.

Is it possible that some networking component in Docker is choking the API calls? Does the problem happen with other API commands once you're authenticated? Can you post the output of the command with `-vvv` when it hangs?

**Comment by rfay** [comment] 2021-02-25 23:00
Thanks for the quick response. I haven't been able to get a clear reading on this, but it's way frequent. My assumption was that it was related to the type of terminal in use, although the exec that's happening here should result in istty() being basically the same. 

Keys:
* Debian 10 container
* Docker
* `acli auth_login` being done via exec, should be identical to `docker exec -it <container> acli auth:login -n --key="${ACQUIA_API_KEY}" --secret="${ACQUIA_API_SECRET}"`

**Comment by danepowell** [comment] 2021-02-26 21:54
I still can't reproduce this. Tried with a Lando container, `docker exec -it bb6433 acli auth:login -n --key="foo" --secret="bar" -vvv` comes back nearly instantly, as expected.

Can you try the latest release (1.7.2) and append `-vvv` and post the full log output as previously requested?

**Comment by rfay** [comment] 2021-02-27 14:22
I'll take a look, but I note that we had a similar problem with drush launcher, https://github.com/drush-ops/drush-launcher/issues/82 - and it turned out to be https://github.com/box-project/box/issues/512 - And I see you're using box as well? Any chance of a correlation?

**Comment by rfay** [comment] 2021-02-28 15:41
I haven't been able to recreate this anywhere; I'm not sure that the version issue was relevant, but it was very, very real. I could watch the execution of acli take too long and watch top while it did, and then see the kill. I've updated to 1.7.2, but think that's probably a red herring. It will be interesting to see if the box issue is relevant, because that was oh-so-similar. But it was also completely recreatable.

**Comment by danepowell** [comment] 2021-03-01 19:24
Good find, https://github.com/box-project/box/issues/512 does seem like a likely culprit. That was fixed in Box 3.11.0. We are using Box 3.8.4. I'm not sure if there's a particular reason that we pinned to 3.8.4, probably we should unpin it.

**Comment by anavarre** [comment] 2021-03-03 18:26
See #455

**Closed** 2021-03-03 19:01 UTC

**Comment by rfay** [comment] 2021-03-18 17:52
FYI I ran up against the situation where it was constantly OOM-killing again, and looked and saw that the docker image I was using still had acli 1.7.1 in it. I updated the image to get 1.8.1, and I haven't seen it again. Fingers crossed. Thanks!
