### ISSUE TITLE
CLI-658: Remove PHP 7.3 checks from PHPCS

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#820] opened 2022-02-17 19:03 UTC
Grumphp is triggering PHPCS which checks for PHP 7.3 requirements we no longer need since ACLI only supports PHP 7.4+ ATM.

```
phpcs
=====

FILE: ...it/acquia/cli/src/Command/CodeStudio/CodeStudioWizardCommand.php
----------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
 32 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 37 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 42 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 47 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 52 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 57 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 62 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 67 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
----------------------------------------------------------------------


FILE: .../phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------
 41 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 42 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 44 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
 45 | ERROR | Typed properties are not supported in PHP 7.3 or
    |       | earlier
----------------------------------------------------------------------
```

**Comment by grasmash** [comment] 2022-02-24 19:48
I think this may come from acquia's coding standards. https://packagist.org/packages/acquia/coding-standards

**Comment by grasmash** [comment] 2022-02-24 19:49
Actually, here's the relevant issue: https://github.com/acquia/coding-standards-php/issues/36

**Comment by grasmash** [comment] 2022-02-24 19:55
@anavarre I can't reproduce this when running `./vendor/bin/phpcs tests/phpunit/src/Commands/CodeStudio/CodeStudioWizardCommandTest.php`

**Comment by grasmash** [comment] 2022-04-22 20:43
This was resolved by updating `acquia/coding-standards` to  `dev-develop`

**Closed by grasmash** 2022-04-22 20:43 UTC
Labels: enhancement
